name = "HeterogeneousComputing"
uuid = "2182be2a-124f-4a91-8389-f06db5907a21"
version = "0.2.3"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"

[extensions]
HeterogeneousComputingCUDAExt = "CUDA"
HeterogeneousComputingKernelAbstractionsExt = "KernelAbstractions"
HeterogeneousComputingStrideArraysExt = "StrideArrays"
HeterogeneousComputingStridedExt = "Strided"

[compat]
Adapt = "3, 4"
CUDA = "3, 4, 5"
KernelAbstractions = "0.8, 0.9"
Random = "1"
StrideArrays = "0.1.28"
Strided = "2"
julia = "1.10"
